openapi: 3.0.0
info:
  contact:
    email: api@factset.com
    name: FactSet Research Systems
    url: https://developer.factset.com/contact
  description: |-
    The Portfolio Reporting Batcher (PRB) API allows clients to systematically leverage functionalities of the PRB application. With the initial release, clients can
    - trigger existing jobs
    - check status of running jobs
    - get various details of existing jobs
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: Portfolio Reporting Batcher
  version: 0.1.0
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/portfolio-reporting-batcher-api
servers:
- url: https://api.factset.com/analytics/prb/v0
security:
- FactSetApiKey: []
- FactSetOAuth2: []
tags:
- description: These endpoints refer to specific runs for a PRB job
  name: Runs
paths:
  /runs:
    post:
      description: Use this endpoint with with POST method to trigger PRB jobs.
      operationId: startJobRun
      requestBody:
        content:
          application/json:
            examples:
              ADF:
                value:
                  data:
                    jobType: ADF
                    jobName: adf_multi_date
                    overrides:
                      dates:
                        start: 2023-11-10
                        end: 2023-12-10
                      frequency: daily
                      calendar: sevenDay
                      runAsSerialNumber: "894550"
              PA:
                value:
                  data:
                    jobType: PA
                    jobName: pa_multi_date
                    overrides:
                      tasks:
                      - task_1
                      - task_2
                      runAsSerialNumber: "894550"
              PD:
                value:
                  data:
                    jobType: PD
                    jobName: my_pd_job
              PI:
                value:
                  data:
                    jobType: PI
                    jobName: my_pi_job
                    overrides:
                      runAsSerialNumber: "894550"
              PUB:
                value:
                  data:
                    jobType: PUB
                    jobName: pub_run_daily
                    overrides:
                      runAsOfDate: 2023-02-05
                      runAsSerialNumber: "894550"
              Vault (No Overrides):
                value:
                  data:
                    jobType: vault
                    jobName: vault_multi_date
              Vault (With Overrides):
                value:
                  data:
                    jobType: vault
                    jobName: vault_multi_date
                    overrides:
                      combinations:
                      - accounts:
                        - CLIENT:/FPS/VAULTED_RETURNS/7DAYS_VLT.ACCT
                        - CLIENT:/FPS/VAULTED_RETURNS/1MONTH.ACCT
                        dates:
                        - 2022-12-24
                        - 2022-12-23
            schema:
              $ref: '#/components/schemas/startJobRoot'
        description: The main object in the request body contains details for the
          job to be triggered. The "name" and "type" fields will uniquely identify
          the job and both must be provided. Other fields can be provided depending
          on the job's type.
      responses:
        "202":
          content:
            application/json:
              examples:
                ADF:
                  value:
                    data:
                      jobName: adf_multi_date
                      jobType: ADF
                      id: "123456"
                      status: queued
                      prbStatus: pending
              schema:
                $ref: '#/components/schemas/startJobRunResponse'
          description: Expected response, the job has been accepted, please use /runs/{id}/status
            to poll status and check progress
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Limit:
              description: Number of allowed requests for the time window.
              explode: false
              schema:
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Remaining:
              description: Number of requests left for the time window.
              explode: false
              schema:
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Reset:
              description: Number of seconds remaining till rate limit resets.
              explode: false
              schema:
                type: string
              style: simple
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/clientErrorResponse'
          description: Invalid post body parameters.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Limit:
              description: Number of allowed requests for the time window.
              explode: false
              schema:
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Remaining:
              description: Number of requests left for the time window.
              explode: false
              schema:
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Reset:
              description: Number of seconds remaining till rate limit resets.
              explode: false
              schema:
                type: string
              style: simple
        "401":
          description: Missing or invalid authentication.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
        "403":
          description: User is forbidden with current credentials
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Limit:
              description: Number of allowed requests for the time window.
              explode: false
              schema:
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Remaining:
              description: Number of requests left for the time window.
              explode: false
              schema:
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Reset:
              description: Number of seconds remaining till rate limit resets.
              explode: false
              schema:
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/clientErrorResponse'
          description: Not Found - invalid inputs
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Limit:
              description: Number of allowed requests for the time window.
              explode: false
              schema:
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Remaining:
              description: Number of requests left for the time window.
              explode: false
              schema:
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Reset:
              description: Number of seconds remaining till rate limit resets.
              explode: false
              schema:
                type: string
              style: simple
        "429":
          description: Rate limit reached. Wait till the time specified in Retry-After
            header value to make further requests.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
            Retry-After:
              description: Time to wait in seconds before making a new request as
                the rate limit has reached.
              explode: false
              schema:
                type: string
              style: simple
        "500":
          description: Server error. Log the X-DataDirect-Request-Key header to assist
            in troubleshooting.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
        "503":
          description: Request timed out. Retry the request in sometime.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
      summary: trigger PRB jobs
      tags:
      - Runs
      x-contentType: application/json
      x-accepts: application/json
  /runs/{id}/status:
    get:
      description: Use this endpoint to check the status of a run using the id from
        the POST /runs endpoint
      operationId: checkRunStatus
      parameters:
      - description: run id
        explode: false
        in: path
        name: id
        required: true
        schema:
          example: "1013456"
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                ADF (With Overrides):
                  value:
                    data:
                      status: queued
                      prbStatus: pending
                      statusDescription: string
                      inputs:
                        jobName: my_adf_job
                        jobType: ADF
                        overrides:
                          dates:
                            start: 2023-12-25
                            end: 2023-12-27
                          frequency: daily
                          calendar: sevenDay
                          runAsSerialNumber: "894550"
                      id: "34578"
                PA (With Overrides):
                  value:
                    data:
                      status: executing
                      prbStatus: running
                      statusDescription: string
                      inputs:
                        jobName: my_pa_job
                        jobType: PA
                        overrides:
                          tasks:
                          - task_1
                          - task_2
                          runAsSerialNumber: "894550"
                      id: "123456"
                PD (With Overrides):
                  value:
                    data:
                      status: executing
                      prbStatus: running
                      statusDescription: string
                      inputs:
                        jobName: my_pd_job
                        jobType: PD
                        overrides:
                          runAsSerialNumber: "894550"
                      id: "78904"
                PI:
                  value:
                    data:
                      status: queued
                      prbStatus: pending
                      statusDescription: string
                      inputs:
                        jobName: my_pi_job
                        jobType: PI
                      id: "78904"
                PUB (With Overrides):
                  value:
                    data:
                      status: queued
                      prbStatus: pending
                      statusDescription: string
                      inputs:
                        jobName: my_pub_job
                        jobType: PUB
                        overrides:
                          runAsOfDate: 2023-02-05
                      id: "3456789"
                Vault (No Overrides):
                  value:
                    data:
                      inputs:
                        jobName: my_vault_job
                        jobType: vault
                      status: created
                      prbStatus: success
                      statusDescription: job has completed with success
                      id: "123456"
                Vault (With Overrides):
                  value:
                    data:
                      inputs:
                        jobName: my_vault_job
                        jobType: vault
                        overrides:
                          combinations:
                          - accounts:
                            - CLIENT:/FPS/VAULTED_RETURNS/7DAYS_VLT.ACCT
                            - CLIENT:/FPS/VAULTED_RETURNS/1MONTH.ACCT
                            dates:
                            - 2022-12-24
                            - 2022-12-23
                          runAsSerialNumber: "894550"
                      status: created
                      prbStatus: success
                      statusDescription: job has completed with success
                      id: "123456"
              schema:
                $ref: '#/components/schemas/idStatus'
          description: OK
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Limit:
              description: Number of allowed requests for the time window.
              explode: false
              schema:
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Remaining:
              description: Number of requests left for the time window.
              explode: false
              schema:
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Reset:
              description: Number of seconds remaining till rate limit resets.
              explode: false
              schema:
                type: string
              style: simple
        "401":
          description: Missing or invalid authentication.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
        "403":
          description: User is forbidden with current credentials
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Limit:
              description: Number of allowed requests for the time window.
              explode: false
              schema:
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Remaining:
              description: Number of requests left for the time window.
              explode: false
              schema:
                type: string
              style: simple
            X-FactSet-Api-RateLimit-Reset:
              description: Number of seconds remaining till rate limit resets.
              explode: false
              schema:
                type: string
              style: simple
        "429":
          description: Rate limit reached. Wait till the time specified in Retry-After
            header value to make further requests.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
            Retry-After:
              description: Time to wait in seconds before making a new request as
                the rate limit has reached.
              explode: false
              schema:
                type: string
              style: simple
        "500":
          description: Server error. Log the X-DataDirect-Request-Key header to assist
            in troubleshooting.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
        "503":
          description: Request timed out. Retry the request in sometime.
          headers:
            X-DataDirect-Request-Key:
              description: FactSet's request key header.
              explode: false
              schema:
                description: FactSet's request key header.
                type: string
              style: simple
            X-FactSet-Api-Request-Key:
              description: Key to uniquely identify an Analytics API request. Only
                available after successful authentication.
              explode: false
              schema:
                description: Key to uniquely identify an Analytics API request. Only
                  available after successful authentication.
                type: string
              style: simple
      summary: check the status for a particular run ID
      tags:
      - Runs
      x-accepts: application/json
components:
  requestBodies: {}
  responses: {}
  schemas:
    calendar:
      default: fiveDay
      description: Used for ADF jobs only
      enum:
      - fiveDay
      - sevenDay
      example: fiveDay
      title: calendar
      type: string
    clientErrorResponse:
      description: The response schema for reporting errors
      properties:
        errors:
          description: List of errors
          items:
            $ref: '#/components/schemas/error'
          type: array
      type: object
    error:
      description: Full details of any error
      properties:
        code:
          description: The error code
          type: string
        detail:
          description: Explanation specific to the occurrence of the error
          type: string
        id:
          description: Identifier for the error
          type: string
        source:
          $ref: '#/components/schemas/errorSource'
        title:
          description: The title of the error
          type: string
      type: object
    errorSource:
      description: The pointer and parameter of the error
      properties:
        parameter:
          description: Indicates which path or URI query parameter caused the error
          type: string
        pointer:
          description: Pointer to the associated entity in the request body
          type: string
      type: object
    frequency:
      default: daily
      description: Used for ADF job types only. Will determine the frequency between
        the start and end dates.
      enum:
      - daily
      - monthly
      - weekly
      type: string
    idStatus:
      description: Details about the instance of the job run specified via id wrapped
        in a data object
      example:
        data:
          statusDescription: job has completed with success
          inputs:
            jobName: my_pa_job
            overrides:
              runAsSerialNumber: "123456"
              tasks:
              - my_task_1
            jobType: PA
          prbStatus: running
          id: id
          status: queued
      properties:
        data:
          $ref: '#/components/schemas/idStatus_data'
      type: object
    jobOverrides:
      description: If this object is provided, the settings given here will override
        the default settings of the job for the job run (settings will only be used
        temporarily and no changes will be made to the default PRB job). Only certain
        objects can be used for certain job types.
      properties:
        calendar:
          $ref: '#/components/schemas/calendar'
        combinations:
          description: An array of date account combinations
          items:
            $ref: '#/components/schemas/jobOverridesCombinationsRoot'
          type: array
        dates:
          $ref: '#/components/schemas/jobOverrides_dates'
        frequency:
          $ref: '#/components/schemas/frequency'
        runAsOfDate:
          description: PUB
          format: date
          type: string
        runAsSerialNumber:
          description: The FactSet serial number which has the credentials wanted
            to run the job
          type: string
        tasks:
          description: Used only for jobs where type is PA
          items:
            type: string
          type: array
      type: object
    jobOverridesCombinationsRoot:
      description: Used for Vault job type only. This creates a matrix of given accounts
        and dates. When the job is run, it will only run for the accounts and dates
        within this object. (Settings will only be used temporarily and no changes
        will be made to the default PRB job.)
      properties:
        accounts:
          description: An array of accounts
          items:
            type: string
          type: array
        dates:
          description: An array of dates
          items:
            format: date
            type: string
          type: array
      type: object
    jobTypes:
      description: PA - Portfolio Analysis, PUB - Publisher, ADF - Analytics DataFeed,
        PI - Portfolio Insight, PD - Portfolio Dashboard, Portfolio Vault - Vault
      enum:
      - ADF
      - PA
      - PD
      - PI
      - PUB
      - vault
      example: vault
      title: jobTypes
      type: string
    prbStatus:
      description: The status of the job as per the application
      enum:
      - failed
      - pending
      - running
      - soft
      - stopped
      - success
      - warning
      example: running
      title: prbStatus
      type: string
    startJob:
      description: Details required to start a job
      example:
        jobName: my_pa_job
        overrides:
          runAsSerialNumber: "123456"
          tasks:
          - my_task_1
        jobType: PA
      properties:
        jobName:
          description: The name of the PRB job
          type: string
        overrides:
          $ref: '#/components/schemas/jobOverrides'
        jobType:
          $ref: '#/components/schemas/jobTypes'
      required:
      - jobName
      - jobType
      title: startJob
      type: object
    startJobRoot:
      description: Details required to start the job wrapped in a data object
      properties:
        data:
          $ref: '#/components/schemas/startJob'
      type: object
    startJobRunResponse:
      description: Gives details about the run which was requested wrapped in a data
        object
      example:
        data:
          jobName: jobName
          prbStatus: running
          id: id
          jobType: vault
          status: queued
      properties:
        data:
          $ref: '#/components/schemas/startJobRunResponse_data'
      required:
      - data
      type: object
    status:
      description: The status of the job as per FactSets API standards
      enum:
      - cancelled
      - created
      - executing
      - failed
      - queued
      example: queued
      title: status
      type: string
    statusDescription:
      description: Further details on the job's status
      example: job has completed with success
      maxLength: 500
      title: statusDescription
      type: string
    idStatus_data:
      description: Details about the instance of the job run specified via id
      example:
        statusDescription: job has completed with success
        inputs:
          jobName: my_pa_job
          overrides:
            runAsSerialNumber: "123456"
            tasks:
            - my_task_1
          jobType: PA
        prbStatus: running
        id: id
        status: queued
      properties:
        id:
          description: The run ID
          type: string
        inputs:
          $ref: '#/components/schemas/startJob'
        prbStatus:
          $ref: '#/components/schemas/prbStatus'
        status:
          $ref: '#/components/schemas/status'
        statusDescription:
          description: Further details on the job's status
          example: job has completed with success
          maxLength: 500
          title: statusDescription
          type: string
      type: object
    jobOverrides_dates:
      description: Used only for jobs where type is ADF
      properties:
        end:
          description: The end date in format YYYY-MM-DD
          format: date
          type: string
        start:
          description: The start date in format YYYY-MM-DD
          format: date
          type: string
      type: object
    startJobRunResponse_data:
      description: The main object within the startJobRunResponse schema
      example:
        jobName: jobName
        prbStatus: running
        id: id
        jobType: vault
        status: queued
      properties:
        id:
          description: The run ID for the job that has been triggered which is used
            in the /runs/{id}/status endpoint
          type: string
        jobName:
          description: Name of the job
          maxLength: 29
          type: string
        prbStatus:
          $ref: '#/components/schemas/prbStatus'
        status:
          $ref: '#/components/schemas/status'
        jobType:
          $ref: '#/components/schemas/jobTypes'
      required:
      - id
      - jobName
      - jobType
      - prbStatus
      - status
      type: object
  securitySchemes:
    FactSetOAuth2:
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://auth.factset.com/as/token.oauth2
      type: oauth2
    FactSetApiKey:
      scheme: basic
      type: http

