openapi: 3.0.3
info:
  contact:
    email: api@factset.com
    name: FactSet Research Systems
    url: https://developer.factset.com/contact
  description: Collection of endpoints for retrieving StreetAccount headlines and
    filters
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: StreetAccount API
  version: 0.1.0
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/factset-news-api
servers:
- url: https://api.factset.com/research/news/v0
security:
- FactSetApiKey: []
- FactSetOAuth2: []
tags:
- description: Get flattened or structured filters
  name: Filters
- description: Get headlines for a specified view or specified filters
  name: Headlines
- description: Create, edit and delete views
  name: Views
paths:
  /streetaccount/headlines:
    post:
      description: This endpoint will pull all headlines produced by StreetAccount
        and the full story body will be returned by the data set. Filters can be specified
        via the endpoint below.
      operationId: getStreetAccountHeadlines
      requestBody:
        $ref: '#/components/requestBodies/saHeadlinesRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Not Found
      summary: Retrieve StreetAccount headlines for given filters
      tags:
      - Headlines
      x-contentType: application/json
      x-accepts: application/json
  /streetaccount/views/{id}/headlines:
    post:
      description: This endpoint allows you to pull all headlines produced by StreetAccount
        for a saved view. The full story body will be returned by the data set. Views
        can be created via the ‘Create Views’ endpoint.
      operationId: getStreetAccountHeadlinesByView
      parameters:
      - description: view id of the view to return headlines for
        example: SA News View
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/saHeadlinesRequestByView'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Not Found
      summary: Retrieve StreetAccount headlines for given view
      tags:
      - Headlines
      x-contentType: application/json
      x-accepts: application/json
  /streetaccount/views:
    get:
      description: This endpoint allows you to pull the full list of StreetAccount
        views that have been previously saved.
      operationId: getStreetAccountViews
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/views'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal Server Error
      summary: Retrieves StreetAccount search views
      tags:
      - Views
      x-accepts: application/json
  /streetaccount/views/{id}:
    delete:
      description: This endpoint allows you to delete a previously saved StreetAccount
        view.
      operationId: deleteStreetAccountView
      parameters:
      - description: view id of the view to be deleted
        example: SA News View
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createEditDeleteViewResponse'
          description: OK
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal Server Error
      summary: Deletes an existing StreetAccount view
      tags:
      - Views
      x-accepts: application/json
    post:
      description: This endpoint allows you to create a new StreetAccount view. Select
        watchlists/tickers and filters of your choice to create and save a view.
      operationId: createStreetAccountView
      parameters:
      - description: view id of the view which is the be created
        example: SA News View
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/createOrEditViewBody'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createEditDeleteViewResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal Server Error
      summary: Creates and saves a StreetAccount view
      tags:
      - Views
      x-contentType: application/json
      x-accepts: application/json
    put:
      description: This endpoint allows you to edit the criteria used for a previously
        saved StreetAccount view.
      operationId: editStreetAccountView
      parameters:
      - description: view id of the view to be edited
        example: SA News View
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/createOrEditViewBody'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createEditDeleteViewResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal Server Error
      summary: Edits and saves an existing StreetAccount view
      tags:
      - Views
      x-contentType: application/json
      x-accepts: application/json
  /streetaccount/filters:
    get:
      description: Add StreetAccount filters (watchlists, company filters, market
        topics, regions and sectors) to filter down StreetAccount headlines by the
        relevant categories. Set the structured and/or flattened flag. If structured
        flag is set, parent and child filter information will be returned. If flattened
        flag is set, flattened filters will be returned which can be used with the
        headlines and createView endpoints. Both flags can be set to return both sets
        of filters.  If no params are provided it will return both
      operationId: getStreetAccountFilters
      parameters:
      - allowEmptyValue: true
        description: Pass structured to generate a structured view of the available
          filters.
        explode: true
        in: query
        name: structured
        required: false
        schema:
          type: boolean
        style: form
      - allowEmptyValue: true
        description: Pass flattened to generate a structured view of the available
          filters.
        explode: true
        in: query
        name: flattened
        required: false
        schema:
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilterResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Not Found
      summary: Retrieve all StreetAccount filters
      tags:
      - Filters
      x-accepts: application/json
components:
  requestBodies:
    saHeadlinesRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/saHeadlinesRequest'
      description: Filter Body which needs to be sent with request
    saHeadlinesRequestByView:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/saHeadlinesRequestByView'
      description: View body which needs to be sent with request
    createOrEditViewBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/createOrEditViewBody'
      description: Create or Edit View Body which needs to be sent with request
  schemas:
    error:
      properties:
        meta:
          type: object
        errors:
          items:
            $ref: '#/components/schemas/errorObject'
          type: array
      type: object
    errorObject:
      properties:
        id:
          type: string
        title:
          type: string
        code:
          type: string
      type: object
    saHeadlinesRequest:
      properties:
        data:
          $ref: '#/components/schemas/saHeadlinesRequest_data'
        meta:
          $ref: '#/components/schemas/saHeadlinesRequest_meta'
      type: object
    saHeadlinesRequestTickersObject:
      properties:
        name:
          example: S&P 500
          type: string
        value:
          example: SP50
          type: string
        type:
          enum:
          - Index
          - ETF
          - Mutual_Fund
          - Portfolios
          example: Index
          type: string
      type: object
    saHeadlinesRequestByView:
      properties:
        data:
          $ref: '#/components/schemas/saHeadlinesRequestByView_data'
        meta:
          $ref: '#/components/schemas/saHeadlinesRequest_meta'
      type: object
    searchResponse:
      description: Properties in results objects are based on return values
      example:
        data:
          results:
          - docsReferenceUris: Sample URI
            docsId: sa_story_3393235
            docsSymbols:
            - AAPL-US
            - AAPL-US
            docsHeadlines: Sample Headline
            docsStoryBody: Sample Body
            docsStoryDateAndTime: 2022-09-15T06:48:19Z
            docsPrimarySymbols:
            - AAPL-US
            - AAPL-US
            docsSubjects:
            - SA_EARNINGS
            - SA_EARNINGS
          - docsReferenceUris: Sample URI
            docsId: sa_story_3393235
            docsSymbols:
            - AAPL-US
            - AAPL-US
            docsHeadlines: Sample Headline
            docsStoryBody: Sample Body
            docsStoryDateAndTime: 2022-09-15T06:48:19Z
            docsPrimarySymbols:
            - AAPL-US
            - AAPL-US
            docsSubjects:
            - SA_EARNINGS
            - SA_EARNINGS
        meta:
          pagination:
            total: 100
            isEstimatedTotal: false
          requestGuid: requestGuid
      properties:
        data:
          $ref: '#/components/schemas/searchResponse_data'
        meta:
          $ref: '#/components/schemas/searchResponse_meta'
      type: object
    searchResponseArrayObject:
      example:
        docsReferenceUris: Sample URI
        docsId: sa_story_3393235
        docsSymbols:
        - AAPL-US
        - AAPL-US
        docsHeadlines: Sample Headline
        docsStoryBody: Sample Body
        docsStoryDateAndTime: 2022-09-15T06:48:19Z
        docsPrimarySymbols:
        - AAPL-US
        - AAPL-US
        docsSubjects:
        - SA_EARNINGS
        - SA_EARNINGS
      properties:
        docsStoryDateAndTime:
          example: 2022-09-15T06:48:19Z
          type: string
        docsHeadlines:
          example: Sample Headline
          type: string
        docsId:
          example: sa_story_3393235
          type: string
        docsPrimarySymbols:
          items:
            example: AAPL-US
            type: string
          type: array
        docsSymbols:
          items:
            example: AAPL-US
            type: string
          type: array
        docsSubjects:
          items:
            example: SA_EARNINGS
            type: string
          type: array
        docsStoryBody:
          example: Sample Body
          type: string
        docsReferenceUris:
          example: Sample URI
          type: string
      type: object
    createOrEditViewBody:
      properties:
        data:
          $ref: '#/components/schemas/createOrEditViewBody_data'
      type: object
    createOrEditViewTickers:
      properties:
        name:
          example: Russell 1000
          type: string
        value:
          example: R.1000
          type: string
        type:
          enum:
          - Index
          - ETF
          - Holder
          - Mutual_Fund
          - Portfolios
          example: Index
          type: string
      type: object
    createEditDeleteViewResponse:
      description: Properties in object are results of the create or save operation
      example:
        data:
          id: StreetAccount News Summaries Europe
          message:
            view: View created/edited/deleted sucessfully
      properties:
        data:
          $ref: '#/components/schemas/createEditDeleteViewResponse_data'
      type: object
    views:
      description: StreetAccount views
      example:
        data:
        - sectors:
          - Chemicals - Plastics & Rubber
          - Chemicals - Plastics & Rubber
          regions:
          - United States
          - United States
          viewName: Sample View
          topics:
          - 'Market Summaries '
          - 'Market Summaries '
          isPrimary: true
          categories:
          - News Media
          - News Media
          tickers:
          - FDS-US
          - FDS-US
        - sectors:
          - Chemicals - Plastics & Rubber
          - Chemicals - Plastics & Rubber
          regions:
          - United States
          - United States
          viewName: Sample View
          topics:
          - 'Market Summaries '
          - 'Market Summaries '
          isPrimary: true
          categories:
          - News Media
          - News Media
          tickers:
          - FDS-US
          - FDS-US
      properties:
        data:
          items:
            $ref: '#/components/schemas/viewsObject'
          type: array
      type: object
    viewsObject:
      example:
        sectors:
        - Chemicals - Plastics & Rubber
        - Chemicals - Plastics & Rubber
        regions:
        - United States
        - United States
        viewName: Sample View
        topics:
        - 'Market Summaries '
        - 'Market Summaries '
        isPrimary: true
        categories:
        - News Media
        - News Media
        tickers:
        - FDS-US
        - FDS-US
      properties:
        viewName:
          example: Sample View
          type: string
        tickers:
          items:
            example: FDS-US
            type: string
          type: array
        categories:
          items:
            example: News Media
            type: string
          type: array
        topics:
          items:
            example: 'Market Summaries '
            type: string
          type: array
        regions:
          items:
            example: United States
            type: string
          type: array
        sectors:
          items:
            example: Chemicals - Plastics & Rubber
            type: string
          type: array
        isPrimary:
          type: boolean
      type: object
    FilterResponse:
      description: Filters Object
      example:
        data:
          structuredFilters:
            sectors:
            - expanded: true
              children:
              - name: name
                value:
                - value
                - value
              - name: name
                value:
                - value
                - value
              name: name
            - expanded: true
              children:
              - name: name
                value:
                - value
                - value
              - name: name
                value:
                - value
                - value
              name: name
            regions:
            - name: name
              value:
              - 0.8008281904610115
              - 0.8008281904610115
            - name: name
              value:
              - 0.8008281904610115
              - 0.8008281904610115
            topics:
            - children:
              - name: name
                value:
                - value
                - value
              - name: name
                value:
                - value
                - value
              name: name
              value:
              - value
              - value
            - children:
              - name: name
                value:
                - value
                - value
              - name: name
                value:
                - value
                - value
              name: name
              value:
              - value
              - value
            watchlists:
            - name: name
              type: type
              value: value
            - name: name
              type: type
              value: value
            categories:
            - children:
              - name: name
                value:
                - value
                - value
              - name: name
                value:
                - value
                - value
              name: name
              value:
              - value
              - value
            - children:
              - name: name
                value:
                - value
                - value
              - name: name
                value:
                - value
                - value
              name: name
              value:
              - value
              - value
          flattenedFilters:
            sectors:
            - name: Chemical Manufacturing
              value:
              - 106
            - name: Chemical Manufacturing
              value:
              - 106
            regions:
            - name: Canada
              value:
              - 5
            - name: Canada
              value:
              - 5
            topics:
            - name: '13F Summary '
              value:
              - SA_13F_SUMMARY
            - name: '13F Summary '
              value:
              - SA_13F_SUMMARY
            watchlists:
            - name: S&P 500
              type: Index
              value: SP50
            - name: S&P 500
              type: Index
              value: SP50
            categories:
            - name: Dividends
              value:
              - SA_DIVIDENDS
            - name: Dividends
              value:
              - SA_DIVIDENDS
      properties:
        data:
          $ref: '#/components/schemas/FilterResponse_data'
      type: object
    flattenedFilters:
      description: Flattened Filters Object
      example:
        sectors:
        - name: Chemical Manufacturing
          value:
          - 106
        - name: Chemical Manufacturing
          value:
          - 106
        regions:
        - name: Canada
          value:
          - 5
        - name: Canada
          value:
          - 5
        topics:
        - name: '13F Summary '
          value:
          - SA_13F_SUMMARY
        - name: '13F Summary '
          value:
          - SA_13F_SUMMARY
        watchlists:
        - name: S&P 500
          type: Index
          value: SP50
        - name: S&P 500
          type: Index
          value: SP50
        categories:
        - name: Dividends
          value:
          - SA_DIVIDENDS
        - name: Dividends
          value:
          - SA_DIVIDENDS
      properties:
        categories:
          items:
            $ref: '#/components/schemas/flattenedFiltersCategoriesObject'
          type: array
        topics:
          items:
            $ref: '#/components/schemas/flattenedFiltersTopicsObject'
          type: array
        regions:
          items:
            $ref: '#/components/schemas/flattenedFiltersRegionsObject'
          type: array
        sectors:
          items:
            $ref: '#/components/schemas/flattenedFiltersSectorsObject'
          type: array
        watchlists:
          items:
            $ref: '#/components/schemas/flattenedFiltersWatchlistsObject'
          type: array
      type: object
    flattenedFiltersCategoriesObject:
      example:
        name: Dividends
        value:
        - SA_DIVIDENDS
      properties:
        name:
          type: string
        value:
          items:
            type: string
          type: array
      type: object
    flattenedFiltersTopicsObject:
      example:
        name: '13F Summary '
        value:
        - SA_13F_SUMMARY
      properties:
        name:
          type: string
        value:
          items:
            type: string
          type: array
      type: object
    flattenedFiltersRegionsObject:
      example:
        name: Canada
        value:
        - 5
      properties:
        name:
          type: string
        value:
          items:
            type: number
          type: array
      type: object
    flattenedFiltersSectorsObject:
      example:
        name: Chemical Manufacturing
        value:
        - 106
      properties:
        name:
          type: string
        value:
          items:
            type: number
          type: array
      type: object
    flattenedFiltersWatchlistsObject:
      example:
        name: S&P 500
        type: Index
        value: SP50
      properties:
        name:
          type: string
        type:
          type: string
        value:
          type: string
      type: object
    structuredFilters:
      description: Structured Filters Object
      example:
        sectors:
        - expanded: true
          children:
          - name: name
            value:
            - value
            - value
          - name: name
            value:
            - value
            - value
          name: name
        - expanded: true
          children:
          - name: name
            value:
            - value
            - value
          - name: name
            value:
            - value
            - value
          name: name
        regions:
        - name: name
          value:
          - 0.8008281904610115
          - 0.8008281904610115
        - name: name
          value:
          - 0.8008281904610115
          - 0.8008281904610115
        topics:
        - children:
          - name: name
            value:
            - value
            - value
          - name: name
            value:
            - value
            - value
          name: name
          value:
          - value
          - value
        - children:
          - name: name
            value:
            - value
            - value
          - name: name
            value:
            - value
            - value
          name: name
          value:
          - value
          - value
        watchlists:
        - name: name
          type: type
          value: value
        - name: name
          type: type
          value: value
        categories:
        - children:
          - name: name
            value:
            - value
            - value
          - name: name
            value:
            - value
            - value
          name: name
          value:
          - value
          - value
        - children:
          - name: name
            value:
            - value
            - value
          - name: name
            value:
            - value
            - value
          name: name
          value:
          - value
          - value
      properties:
        categories:
          items:
            $ref: '#/components/schemas/structuredFiltersCategoriesObject'
          type: array
        topics:
          items:
            $ref: '#/components/schemas/structuredFiltersTopicsObject'
          type: array
        regions:
          items:
            $ref: '#/components/schemas/structuredFiltersRegionsObject'
          type: array
        sectors:
          items:
            $ref: '#/components/schemas/structuredFiltersSectorsObject'
          type: array
        watchlists:
          items:
            $ref: '#/components/schemas/structuredFiltersWatchlistsObject'
          type: array
      type: object
    structuredFiltersCategoriesObject:
      example:
        children:
        - name: name
          value:
          - value
          - value
        - name: name
          value:
          - value
          - value
        name: name
        value:
        - value
        - value
      properties:
        name:
          type: string
        value:
          items:
            type: string
          type: array
        children:
          items:
            $ref: '#/components/schemas/structuredFiltersChildrenObject'
          type: array
      type: object
    structuredFiltersChildrenObject:
      example:
        name: name
        value:
        - value
        - value
      properties:
        name:
          type: string
        value:
          items:
            type: string
          type: array
      type: object
    structuredFiltersTopicsObject:
      example:
        children:
        - name: name
          value:
          - value
          - value
        - name: name
          value:
          - value
          - value
        name: name
        value:
        - value
        - value
      properties:
        name:
          type: string
        value:
          items:
            type: string
          type: array
        children:
          items:
            $ref: '#/components/schemas/structuredFiltersChildrenObject'
          type: array
      type: object
    structuredFiltersRegionsObject:
      example:
        name: name
        value:
        - 0.8008281904610115
        - 0.8008281904610115
      properties:
        name:
          type: string
        value:
          items:
            type: number
          type: array
      type: object
    structuredFiltersSectorsObject:
      example:
        expanded: true
        children:
        - name: name
          value:
          - value
          - value
        - name: name
          value:
          - value
          - value
        name: name
      properties:
        name:
          type: string
        expanded:
          type: boolean
        children:
          items:
            $ref: '#/components/schemas/structuredFiltersChildrenObject'
          type: array
      type: object
    structuredFiltersWatchlistsObject:
      example:
        name: name
        type: type
        value: value
      properties:
        name:
          type: string
        type:
          type: string
        value:
          type: string
      type: object
    saHeadlinesRequest_data_searchDate:
      properties:
        start:
          description: Start time for custom search. startTime must follow the ISO
            8601 standard format, YYYY-MM-DDTHH:mm:ssZ (UTC). It also supports offsets
            ±[hh]:[mm]
          example: 2022-08-21T12:35:45Z
          type: string
        end:
          description: End time for custom search. If end time is not present end
            time is automatically set to the time of the search. endTime must follow
            the ISO 8601 standard format, YYYY-MM-DDTHH:mm:ssZ (UTC). It also supports
            offsets ±[hh]:[mm]
          example: 2022-08-29T08:10:30Z
          type: string
      type: object
    saHeadlinesRequest_data:
      properties:
        tickers:
          items:
            $ref: '#/components/schemas/saHeadlinesRequestTickersObject'
          type: array
        categories:
          items:
            example: Earnings
            type: string
          type: array
        regions:
          items:
            example: United States
            type: string
          type: array
        topics:
          items:
            example: Market Summaries
            type: string
          type: array
        sectors:
          items:
            example: Gold & Silver
            type: string
          type: array
        isPrimary:
          example: true
          type: boolean
        dateRange:
          description: see list of valid date ranges. Date range is mutually exlusive
            to start/end time
          enum:
          - Today
          - 2 Days
          - 1 Week
          - 1 Month
          - 3 Months
          - 6 Months
          - 1 Year
          - 3 Years
          - 5 Years
          - 10 Years
          - All Available
          type: string
        searchDate:
          $ref: '#/components/schemas/saHeadlinesRequest_data_searchDate'
      type: object
    saHeadlinesRequest_meta_pagination:
      description: Object defining pagination for the results pageable attribute.
        Offset-based strategy is used for Pagination.
      properties:
        limit:
          default: 500
          description: Non-negative maximum number of entries to return.
          example: 50
          type: integer
        offset:
          default: 0
          description: Non-negative number of entries to skip.
          example: 100
          type: integer
      type: object
    saHeadlinesRequest_meta:
      properties:
        pagination:
          $ref: '#/components/schemas/saHeadlinesRequest_meta_pagination'
      type: object
    saHeadlinesRequestByView_data:
      properties:
        dateRange:
          description: see list of valid date ranges. Date range is mutually exlusive
            to start/end time
          enum:
          - Today
          - 2 Days
          - 1 Week
          - 1 Month
          - 3 Months
          - 6 Months
          - 1 Year
          - 3 Years
          - 5 Years
          - 10 Years
          - All Available
          type: string
        searchDate:
          $ref: '#/components/schemas/saHeadlinesRequest_data_searchDate'
      type: object
    searchResponse_data:
      example:
        results:
        - docsReferenceUris: Sample URI
          docsId: sa_story_3393235
          docsSymbols:
          - AAPL-US
          - AAPL-US
          docsHeadlines: Sample Headline
          docsStoryBody: Sample Body
          docsStoryDateAndTime: 2022-09-15T06:48:19Z
          docsPrimarySymbols:
          - AAPL-US
          - AAPL-US
          docsSubjects:
          - SA_EARNINGS
          - SA_EARNINGS
        - docsReferenceUris: Sample URI
          docsId: sa_story_3393235
          docsSymbols:
          - AAPL-US
          - AAPL-US
          docsHeadlines: Sample Headline
          docsStoryBody: Sample Body
          docsStoryDateAndTime: 2022-09-15T06:48:19Z
          docsPrimarySymbols:
          - AAPL-US
          - AAPL-US
          docsSubjects:
          - SA_EARNINGS
          - SA_EARNINGS
      properties:
        results:
          items:
            $ref: '#/components/schemas/searchResponseArrayObject'
          type: array
      type: object
    searchResponse_meta_pagination:
      example:
        total: 100
        isEstimatedTotal: false
      properties:
        total:
          example: 100
          type: integer
        isEstimatedTotal:
          example: false
          type: boolean
      type: object
    searchResponse_meta:
      example:
        pagination:
          total: 100
          isEstimatedTotal: false
        requestGuid: requestGuid
      properties:
        requestGuid:
          type: string
        pagination:
          $ref: '#/components/schemas/searchResponse_meta_pagination'
      type: object
    createOrEditViewBody_data:
      properties:
        tickers:
          items:
            $ref: '#/components/schemas/createOrEditViewTickers'
          type: array
        categories:
          items:
            example: Earnings
            type: string
          type: array
        regions:
          items:
            example: United States
            type: string
          type: array
        topics:
          items:
            example: Market Summaries
            type: string
          type: array
        sectors:
          items:
            example: Gold & Silver
            type: string
          type: array
        isPrimary:
          example: true
          type: boolean
        quickAlert:
          example: false
          type: boolean
      type: object
    createEditDeleteViewResponse_data_message:
      example:
        view: View created/edited/deleted sucessfully
      properties:
        view:
          example: View created/edited/deleted sucessfully
          type: string
      type: object
    createEditDeleteViewResponse_data:
      example:
        id: StreetAccount News Summaries Europe
        message:
          view: View created/edited/deleted sucessfully
      properties:
        id:
          example: StreetAccount News Summaries Europe
          type: string
        message:
          $ref: '#/components/schemas/createEditDeleteViewResponse_data_message'
      type: object
    FilterResponse_data:
      example:
        structuredFilters:
          sectors:
          - expanded: true
            children:
            - name: name
              value:
              - value
              - value
            - name: name
              value:
              - value
              - value
            name: name
          - expanded: true
            children:
            - name: name
              value:
              - value
              - value
            - name: name
              value:
              - value
              - value
            name: name
          regions:
          - name: name
            value:
            - 0.8008281904610115
            - 0.8008281904610115
          - name: name
            value:
            - 0.8008281904610115
            - 0.8008281904610115
          topics:
          - children:
            - name: name
              value:
              - value
              - value
            - name: name
              value:
              - value
              - value
            name: name
            value:
            - value
            - value
          - children:
            - name: name
              value:
              - value
              - value
            - name: name
              value:
              - value
              - value
            name: name
            value:
            - value
            - value
          watchlists:
          - name: name
            type: type
            value: value
          - name: name
            type: type
            value: value
          categories:
          - children:
            - name: name
              value:
              - value
              - value
            - name: name
              value:
              - value
              - value
            name: name
            value:
            - value
            - value
          - children:
            - name: name
              value:
              - value
              - value
            - name: name
              value:
              - value
              - value
            name: name
            value:
            - value
            - value
        flattenedFilters:
          sectors:
          - name: Chemical Manufacturing
            value:
            - 106
          - name: Chemical Manufacturing
            value:
            - 106
          regions:
          - name: Canada
            value:
            - 5
          - name: Canada
            value:
            - 5
          topics:
          - name: '13F Summary '
            value:
            - SA_13F_SUMMARY
          - name: '13F Summary '
            value:
            - SA_13F_SUMMARY
          watchlists:
          - name: S&P 500
            type: Index
            value: SP50
          - name: S&P 500
            type: Index
            value: SP50
          categories:
          - name: Dividends
            value:
            - SA_DIVIDENDS
          - name: Dividends
            value:
            - SA_DIVIDENDS
      properties:
        structuredFilters:
          $ref: '#/components/schemas/structuredFilters'
        flattenedFilters:
          $ref: '#/components/schemas/flattenedFilters'
      type: object
  securitySchemes:
    FactSetOAuth2:
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://auth.factset.com/as/token.oauth2
      type: oauth2
    FactSetApiKey:
      scheme: basic
      type: http

